import { Command } from "commander";
import chalk from "chalk";
import { createInterface } from "readline";
import { existsSync, mkdirSync, readFileSync, writeFileSync, appendFileSync } from "fs";
import { resolve } from "path";
import { loadSettings, saveSettings } from "../settings.js";
import { PerpError } from "../errors.js";
import { jsonOk, jsonError, printJson } from "../utils.js";
import { resolvePassphrase } from "../agent-wallet/passphrase.js";
import { loadOws } from "../signer/ows-loader.js";

const PERP_DIR = resolve(process.env.HOME || "~", ".perp");
const ENV_FILE = resolve(PERP_DIR, ".env");

// ── .env helpers ──────────────────────────────────────────────

export { ENV_FILE, loadEnvFile, setEnvVar };

function ensurePerpDir() {
  if (!existsSync(PERP_DIR)) mkdirSync(PERP_DIR, { recursive: true, mode: 0o700 });
}

function loadEnvFile(): Record<string, string> {
  if (!existsSync(ENV_FILE)) return {};
  const lines = readFileSync(ENV_FILE, "utf-8").split("\n");
  const env: Record<string, string> = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx > 0) {
      env[trimmed.slice(0, eqIdx)] = trimmed.slice(eqIdx + 1);
    }
  }
  return env;
}

function writeEnvFile(env: Record<string, string>) {
  ensurePerpDir();
  const lines = [
    "# perp-cli configuration",
    "# Generated by 'perp setup' — edit freely",
    "",
  ];
  for (const [key, value] of Object.entries(env)) {
    lines.push(`${key}=${value}`);
  }
  lines.push("");
  writeFileSync(ENV_FILE, lines.join("\n"), { mode: 0o600 });
}

function setEnvVar(key: string, value: string) {
  ensurePerpDir();
  const env = loadEnvFile();
  env[key] = value;
  writeEnvFile(env);
  // Also set in current process
  process.env[key] = value;
}

// ── Interactive helpers ───────────────────────────────────────

function ask(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
  return new Promise((resolve) => rl.question(question, (answer) => resolve(answer.trim())));
}

function askChoice(rl: ReturnType<typeof createInterface>, question: string, choices: string[]): Promise<string> {
  return new Promise((resolve) => {
    const choiceStr = choices.map((c, i) => `${i + 1}) ${c}`).join("  ");
    rl.question(`${question} [${choiceStr}]: `, (answer) => {
      const trimmed = answer.trim();
      const idx = parseInt(trimmed) - 1;
      if (idx >= 0 && idx < choices.length) return resolve(choices[idx]);
      const match = choices.find((c) => c.toLowerCase().startsWith(trimmed.toLowerCase()));
      resolve(match || choices[0]);
    });
  });
}

// ── Exchange → env var mapping ────────────────────────────────

// v0.12.4 retired the legacy HMAC ASTER_API_KEY/SECRET path (Plan v3.0).
// v0.12.6 restores Aster as a normal EVM exchange: `ASTER_PRIVATE_KEY`
// (Tier 3 PK direct path) is collected like HL/LT, and the agent flow
// (`wallet agent approve aster`) is the recommended Tier 1 onboarding.
// Removing Aster entirely was over-correction — the entry must exist so
// `wallet import` / `wallet set` / setup wizard treat all 4 DEX uniformly.
export const EXCHANGE_ENV_MAP: Record<string, { envKey: string; envKeySecret?: string; chain: "solana" | "evm" | "apikey"; label: string }> = {
  pacifica: { envKey: "PACIFICA_PRIVATE_KEY", chain: "solana", label: "Pacifica (Solana)" },
  hyperliquid: { envKey: "HL_PRIVATE_KEY", chain: "evm", label: "Hyperliquid (EVM)" },
  lighter: { envKey: "LIGHTER_PRIVATE_KEY", chain: "evm", label: "Lighter (EVM)" },
  aster: { envKey: "ASTER_PRIVATE_KEY", chain: "evm", label: "Aster (BNB Chain)" },
};

// ── Validate keys ─────────────────────────────────────────────

export async function validateKey(chain: "solana" | "evm" | "apikey", key: string): Promise<{ valid: boolean; address: string }> {
  if (chain === "solana") {
    try {
      const { Keypair } = await import("@solana/web3.js");
      const bs58 = (await import("bs58")).default;
      try {
        const kp = Keypair.fromSecretKey(bs58.decode(key));
        return { valid: true, address: kp.publicKey.toBase58() };
      } catch {
        const arr = JSON.parse(key);
        const kp = Keypair.fromSecretKey(Uint8Array.from(arr));
        return { valid: true, address: kp.publicKey.toBase58() };
      }
    } catch {
      return { valid: false, address: "" };
    }
  } else if (chain === "apikey") {
    // API key validation: just check it's a non-empty hex-like string
    return { valid: key.length >= 16, address: key.slice(0, 8) + "..." + key.slice(-4) };
  } else {
    try {
      const { ethers } = await import("ethers");
      const pk = key.startsWith("0x") ? key : `0x${key}`;
      return { valid: true, address: new ethers.Wallet(pk).address };
    } catch {
      return { valid: false, address: "" };
    }
  }
}

// ── Commands ──────────────────────────────────────────────────

export function registerInitCommand(program: Command) {
  // ── perp setup (interactive + non-interactive) ──
  program
    .command("setup")
    .alias("init")
    .description("Setup wizard — interactive by default, scriptable with --non-interactive")
    .option("--non-interactive", "Run without prompts; requires --passphrase or OWS_PASSPHRASE env")
    .option("--wallet-name <name>", "OWS wallet alias to create (default: 'main')")
    .option("--passphrase <pp>", "OWS vault passphrase (fallback: OWS_PASSPHRASE env / stdin)")
    .option("--default-exchange <name>", "Default exchange (pacifica/hyperliquid/lighter/aster)")
    .action(async (opts: {
      nonInteractive?: boolean;
      walletName?: string;
      passphrase?: string;
      defaultExchange?: string;
    }, command: Command) => {
      // optsWithGlobals() merges parent + subcommand options so --passphrase
      // works whether placed on `perp --passphrase X setup` (parent) or
      // `perp setup --passphrase X` (subcommand). Commander v13 silently
      // shadows the subcommand flag when the parent defines an identically
      // named flag — the visible bug was non-interactive setup throwing
      // PASSPHRASE_REQUIRED with --passphrase set on the subcommand.
      const mergedOpts = command.optsWithGlobals() as { passphrase?: string };
      const resolvedOpts = {
        ...opts,
        passphrase: mergedOpts.passphrase ?? opts.passphrase,
      };

      // Non-interactive mode: skip all readline prompts, drive everything from
      // flags + OWS_PASSPHRASE env. This is the agent-friendly onboarding path
      // (CI / Docker / scripted init) — see plan v3.0 "agent-friendly five
      // guarantees" P1 (no-prompt) and P3 (passphrase 3-path).
      if (resolvedOpts.nonInteractive) {
        return runNonInteractiveSetup(resolvedOpts);
      }

      const rl = createInterface({ input: process.stdin, output: process.stdout });

      try {
        console.log(chalk.cyan.bold("\n  perp-cli Setup Wizard\n"));

        // Show current state
        const env = loadEnvFile();
        const configured: string[] = [];
        for (const [exchange, info] of Object.entries(EXCHANGE_ENV_MAP)) {
          if (env[info.envKey] || process.env[info.envKey]) {
            configured.push(exchange);
          }
        }

        if (configured.length > 0) {
          console.log(chalk.white("  Already configured:"));
          for (const ex of configured) {
            const info = EXCHANGE_ENV_MAP[ex];
            const key = env[info.envKey] || process.env[info.envKey] || "";
            const masked = key.slice(0, 6) + "..." + key.slice(-4);
            console.log(`    ${chalk.cyan(ex.padEnd(14))} ${chalk.gray(masked)}`);
          }
          console.log();
          const action = await askChoice(rl, "  Add/update keys or exit?", ["update", "exit"]);
          if (action === "exit") {
            rl.close();
            return;
          }
        }

        // Select exchanges
        console.log(chalk.white("  Exchanges:"));
        console.log(`    1) ${chalk.cyan("Pacifica")}    ${chalk.gray("— Solana perps (USDC on Solana)")}`);
        console.log(`    2) ${chalk.cyan("Hyperliquid")} ${chalk.gray("— EVM perps (USDC on Arbitrum)")}`);
        console.log(`    3) ${chalk.cyan("Lighter")}     ${chalk.gray("— EVM perps (USDC on Ethereum/Arb)")}`);
        console.log(`    4) ${chalk.cyan("Aster")}       ${chalk.gray("— BNB Chain perps (use 'wallet agent approve aster')")}`);
        console.log();

        const exchangeChoice = await ask(rl, "  Which exchange(s)? (1,2,3,4 or 'all'): ");
        const selected = parseExchangeChoice(exchangeChoice);

        if (selected.length === 0) {
          console.log(chalk.red("\n  No exchanges selected.\n"));
          rl.close();
          return;
        }

        // Collect keys per exchange
        // EVM exchanges can share the same key
        const evmExchanges = selected.filter((e) => EXCHANGE_ENV_MAP[e].chain === "evm");
        const solExchanges = selected.filter((e) => EXCHANGE_ENV_MAP[e].chain === "solana");
        const newEnv = { ...env };

        if (evmExchanges.length > 0) {
          console.log(chalk.cyan.bold("\n  EVM Private Key") + chalk.gray(` (for ${evmExchanges.join(", ")})`));

          // Check if they share one key
          let sharedKey = "";
          if (evmExchanges.length > 1) {
            const share = await askChoice(rl, "  Use same key for all EVM exchanges?", ["yes", "no"]);
            if (share === "yes") {
              sharedKey = await ask(rl, "  EVM private key (0x...): ");
              const { valid, address } = await validateKey("evm", sharedKey);
              if (!valid) {
                console.log(chalk.red("  Invalid EVM key."));
                rl.close();
                return;
              }
              const normalized = sharedKey.startsWith("0x") ? sharedKey : `0x${sharedKey}`;
              console.log(`  ${chalk.green("OK")} ${chalk.gray(address)}`);
              for (const ex of evmExchanges) {
                newEnv[EXCHANGE_ENV_MAP[ex].envKey] = normalized;
              }
            }
          }

          if (!sharedKey) {
            for (const ex of evmExchanges) {
              const info = EXCHANGE_ENV_MAP[ex];
              const key = await ask(rl, `  ${info.label} private key (0x...): `);
              if (!key) { console.log(chalk.gray("  Skipped.")); continue; }
              const { valid, address } = await validateKey("evm", key);
              if (!valid) { console.log(chalk.red("  Invalid key, skipped.")); continue; }
              const normalized = key.startsWith("0x") ? key : `0x${key}`;
              newEnv[info.envKey] = normalized;
              console.log(`  ${chalk.green("OK")} ${chalk.gray(address)}`);
            }
          }
        }

        if (solExchanges.length > 0) {
          console.log(chalk.cyan.bold("\n  Solana Private Key") + chalk.gray(" (for Pacifica)"));
          const key = await ask(rl, "  Solana private key (base58): ");
          if (key) {
            const { valid, address } = await validateKey("solana", key);
            if (valid) {
              newEnv.PACIFICA_PRIVATE_KEY = key;
              console.log(`  ${chalk.green("OK")} ${chalk.gray(address)}`);
            } else {
              console.log(chalk.red("  Invalid Solana key, skipped."));
            }
          }
        }

        // v0.12.4: API-key (Aster legacy HMAC) onboarding removed from the
        // wizard. Aster users follow the redirect above to
        // `perp wallet agent approve aster`.

        // Default exchange
        const settings = loadSettings();
        if (selected.length === 1) {
          settings.defaultExchange = selected[0];
        } else if (!settings.defaultExchange) {
          const defaultEx = await askChoice(rl, "\n  Default exchange?", selected);
          settings.defaultExchange = defaultEx;
        }
        saveSettings(settings);

        // Write .env
        writeEnvFile(newEnv);

        // Summary
        console.log(chalk.cyan.bold("\n  Setup Complete!\n"));
        console.log(`  Config:   ${chalk.gray("~/.perp/.env")}`);
        console.log(`  Default:  ${chalk.cyan(settings.defaultExchange || selected[0])}`);

        for (const ex of selected) {
          const info = EXCHANGE_ENV_MAP[ex];
          const key = newEnv[info.envKey];
          if (key) {
            console.log(`  ${chalk.cyan(ex.padEnd(14))} ${chalk.green("configured")}`);
          }
        }

        console.log(chalk.white.bold("\n  Next steps:"));
        console.log(`    ${chalk.green("perp portfolio")}                  balances + positions + risk`);
        if (selected.includes("hyperliquid")) {
          console.log(`    ${chalk.green("perp deposit hyperliquid <amt>")}   deposit USDC`);
        }
        if (selected.includes("pacifica")) {
          console.log(`    ${chalk.green("perp deposit pacifica <amt>")}      deposit USDC`);
        }
        console.log(`    ${chalk.green("perp market list")}                 browse markets`);
        console.log(`    ${chalk.green("perp dashboard")}                   live monitoring\n`);

        rl.close();
      } catch (err) {
        rl.close();
        throw err;
      }
    });

}

function parseExchangeChoice(input: string): string[] {
  const lower = input.toLowerCase().trim();
  if (lower === "all" || lower === "1,2,3,4") return ["pacifica", "hyperliquid", "lighter", "aster"];
  if (lower === "1,2,3") return ["pacifica", "hyperliquid", "lighter"];

  const exchanges: string[] = [];
  const parts = lower.split(/[,\s]+/);
  for (const p of parts) {
    if (p === "1" || p.startsWith("pac")) exchanges.push("pacifica");
    else if (p === "2" || p.startsWith("hyp") || p === "hl") exchanges.push("hyperliquid");
    else if (p === "3" || p.startsWith("lig") || p === "lt") exchanges.push("lighter");
    else if (p === "4" || p.startsWith("ast")) exchanges.push("aster");
  }
  return [...new Set(exchanges)];
}

// ── Non-interactive setup (agent / CI / Docker) ──────────────────────────────

const VALID_EXCHANGES = ["pacifica", "hyperliquid", "lighter", "aster"] as const;

/**
 * Test seam: emit JSON envelopes when the global --json flag is present.
 * Mirrors the inline pattern used elsewhere (see src/index.ts:87) instead of
 * wiring isJson() through registerInitCommand for one call site.
 */
function setupIsJson(): boolean {
  return process.argv.includes("--json");
}

/**
 * Drive `perp setup` end-to-end without TTY. Required:
 *   - --passphrase or OWS_PASSPHRASE env (3-path resolver)
 * Optional:
 *   - --wallet-name (default: "main")
 *   - --default-exchange (must be one of pacifica/hyperliquid/lighter/aster)
 *
 * Side effects:
 *   1. Creates an OWS wallet via createWallet(name, passphrase)
 *   2. Sets settings.owsActiveWallet (if unset) + settings.defaultExchange (if provided)
 *
 * Errors are returned as INVALID_PARAMS / PASSPHRASE_REQUIRED — never via
 * readline. JSON envelope is emitted on stdout when --json is present.
 */
export async function runNonInteractiveSetup(opts: {
  walletName?: string;
  passphrase?: string;
  defaultExchange?: string;
}): Promise<void> {
  const isJson = setupIsJson();

  try {
    // Validate --default-exchange shape early so users hit a precise error
    // before passphrase resolution.
    if (
      opts.defaultExchange !== undefined &&
      !(VALID_EXCHANGES as readonly string[]).includes(opts.defaultExchange)
    ) {
      throw new PerpError(
        "INVALID_PARAMS",
        `Invalid --default-exchange "${opts.defaultExchange}"`,
        {
          remediation: `Use one of: ${VALID_EXCHANGES.join(", ")}`,
        },
      );
    }

    // Resolve passphrase. resolvePassphrase already throws PASSPHRASE_REQUIRED
    // when stdin is non-TTY and nothing was provided. In TTY mode it returns
    // null — non-interactive mode must NOT fall back to a prompt.
    const resolved = await resolvePassphrase({ flag: opts.passphrase });
    if (resolved === null) {
      throw new PerpError(
        "PASSPHRASE_REQUIRED",
        "Non-interactive setup requires a passphrase",
        {
          remediation: "Provide --passphrase <pp> or set OWS_PASSPHRASE env var",
        },
      );
    }
    const pp = resolved;

    const walletName = opts.walletName ?? "main";

    // Create OWS wallet
    const ows = loadOws();
    const w = ows.createWallet(walletName, pp);

    // Update settings
    const settings = loadSettings();
    if (!settings.owsActiveWallet) {
      settings.owsActiveWallet = walletName;
    }
    if (opts.defaultExchange) {
      settings.defaultExchange = opts.defaultExchange;
    }
    saveSettings(settings);

    if (isJson) {
      printJson(
        jsonOk({
          walletName: w.name,
          walletId: w.id,
          accounts: w.accounts,
          owsActiveWallet: settings.owsActiveWallet,
          defaultExchange: settings.defaultExchange ?? null,
          mode: "non-interactive",
        }),
      );
      return;
    }

    console.log(chalk.cyan.bold("\n  perp-cli Setup (non-interactive) — Done\n"));
    console.log(`  Wallet:           ${chalk.white.bold(w.name)}`);
    console.log(`  Active wallet:    ${chalk.cyan(settings.owsActiveWallet)}`);
    if (settings.defaultExchange) {
      console.log(`  Default exchange: ${chalk.cyan(settings.defaultExchange)}`);
    }
    console.log(chalk.gray(`\n  Vault: ~/.ows/ (AES-256-GCM encrypted)\n`));
  } catch (err) {
    if (isJson) {
      if (err instanceof PerpError) {
        printJson(
          jsonError(err.structured.code, err.structured.message, {
            ...(err.structured.remediation
              ? { details: { remediation: err.structured.remediation } }
              : {}),
          }),
        );
      } else {
        const msg = err instanceof Error ? err.message : String(err);
        printJson(jsonError("UNKNOWN", msg));
      }
      process.exitCode = 1;
      return;
    }
    if (err instanceof PerpError) {
      console.error(chalk.red(`\n  Error [${err.structured.code}]: ${err.structured.message}`));
      if (err.structured.remediation) {
        console.error(chalk.gray(`  Remediation: ${err.structured.remediation}\n`));
      }
    } else {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(chalk.red(`\n  Error: ${msg}\n`));
    }
    process.exitCode = 1;
  }
}
